### GET a specific book
GET http://localhost:3000/api/books/6a2a35d9d859a9ad271b25d2
content-type: application/json

### GET all books
GET http://localhost:3000/api/books
content-type: application/json

### Create a book
POST http://localhost:3000/api/books
content-type: application/json

{
    "title": "Sample",
    "author": "Jhon Doe",
    "pages": 200
}

### Patch a book
PATCH http://localhost:3000/api/books/6a2a35d9d859a9ad271b25d2
Content-Type: application/json

{
    "title": "updated title"
}


### DELETE a book
DELETE http://localhost:3000/api/books/6a2a359dd859a9ad271b25d1
Content-Type: application/json
